config/routes.rb
Rails.application.routes.draw do
  get 'session/new'
  get 'session/create'
  get 'session/destroy'
  get 'admin/index'
  resources :users
  get 'manager/index'
  resources :books
  resources :cartegories
  root to: 'manager#index'
  
   get 'admin' => 'admin#index'
    get 'register' => 'users#new'
      controller :session do
        get 'login' => :new
        post 'login' => :create
        delete 'logout' => :destroy
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
	skip_before_action :authorize
  def new
  end

  def create
	if user = User.authenticate(params[:name],params[:password])
		session[:user_id] = user.id
		redirect_to admin_url
	else
		redirect_to login_url, :alert => "Invaild username/password"
	end
  end

  def destroy
	session[:user_id] = nil
	redirect_to '/', :notice => "Logged out"
  end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/session/create.html.erb
<h1>Sessions#create</h1>
<p>Find me in app/views/sessions/create.html.erb</p>

app/views/session/destroy.html.erb
<h1>Sessions#destroy</h1>
<p>Find me in app/views/sessions/destroy.html.erb</p>

app/views/session/new.html.erb
<div class="book_form">
    <% if flash[:alert] %>
        <p id="notice"><%= flash[:alert] %></p>
    <% end %>
  
    <% if notice %>
        <p id="notice"><%= notice %></p>
    <% end %>
    <%= form_tag '/login' do %>
        <fieldset>
            <legend>Log In</legend>
  
            <div>
                <label for="name">Name:</label>
                <%= text_field_tag :name, params[:name] %>
            </div>
  
            <div>
                <label for="password">Password:</label>
                <%= password_field_tag :password, params[:password] %>
            </div>
  
            <div>
                <%= submit_tag "Login" %>
                <span col="3"><%=link_to 'Register', register_url%></span>
            </div>

        </fieldset>
    <% end %>
</div>