config/routes.rb
Rails.application.routes.draw do
  get 'session/new'
  get 'session/create'
  get 'session/destroy'
  get 'admin/index'
  resources :users
  get 'manager/index'
  resources :books
  resources :cartegories
  root to: 'manager#index'
  
   get 'admin' => 'admin#index'
    get 'register' => 'users#new'
      controller :session do
        get 'login' => :new
        post 'login' => :create
        delete 'logout' => :destroy
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
require 'digest/sha2'

class User < ApplicationRecord
	validates :user_name, :email, :presence => true, :uniqueness => true
	validates :password, :confirmation => true
	validates_length_of :user_name, :minimum => 6
	validates_format_of :password, :with => /\A(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[A-Za-z\d]{8,}\z/
	attr_accessor :password_confirmation
	attr_reader :password

	validate :password_must_be_present
	before_destroy :check_if_has_confirmed

	ROLE_ENUM = [ "Admin","Editor"]

	def User.encrypt_password(password, salt)
		Digest::SHA2.hexdigest(password + salt)
	end

	def password=(password)
		@password = password
		if password.present?
			generate_salt
			self.hashed_password = self.class.encrypt_password(password,salt)
		end
	end

	def User.authenticate(user_name,password)
		if user = find_by_user_name(user_name)
			if user.hashed_password == encrypt_password(password, user.salt)
				user
			end
		end
	end

private
	def password_must_be_present
		if hashed_password.present? == false
			errors.add(:password, "Missing password")
		end
	end

	def generate_salt
		self.salt = self.object_id.to_s + rand.to_s
	end

	def check_if_has_confirmed
		if confirms.empty?
			return true
		else
			return false
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to login_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to login_url, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user_name, :email, :hashed_password, :salt, :role, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="book_form">
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
  <legend>Enter User Details</legend>
  <div class="field">
    <%= form.label :user_name, 'Name' %>
    <%= form.text_field :user_name, :size => 40 %>
  </div>

  <div class="field">
    <%= form.label :email, 'Email' %>
    <%= form.text_field :email, :size => 40 %>
  </div>

  <div class="field">
    <%= form.label :password, 'Password' %>
    <%= form.password_field :password, :size => 40 %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation, 'Confirm'%>
    <%= form.password_field :password_confirmation, :size => 40 %>
  </div>

  <div class="field">
    <%= form.label :role, 'Role' %><br>
    <%= form.select :role, User::ROLE_ENUM, :prompt => "Select a role..." %>
  </div>

 <div class="actions">
    <%= submit_tag 'Create User'%>
  </div>
  </fieldset>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.user_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.user_name %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @user.created_at %>
</p>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>