config/routes.rb
Rails.application.routes.draw do
  get 'session/new'
  get 'session/create'
  get 'session/destroy'
  get 'admin/index'
  resources :users
  get 'manager/index'
  resources :books
  resources :cartegories
  root to: 'manager#index'
  
   get 'admin' => 'admin#index'
    get 'register' => 'users#new'
      controller :session do
        get 'login' => :new
        post 'login' => :create
        delete 'logout' => :destroy
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
	validates :book_name, :book_image, :book_author, :presence => true
	validates :book_name, :uniqueness => true
	validates :book_price, :numericality => {:greater_than => 0}
	belongs_to :cartegory
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new

    @cartegories = Cartegory.all
  end

  # GET /books/1/edit
  def edit
    @cartegories = Cartegory.all
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to '/', notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to '/', notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:book_name, :book_image, :book_author, :cartegory_id, :book_price)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<div class = "book_form">
<%= form_with(model: book, local: true) do |form| %>
	 <% if book.errors.any? %>
		<div id="error_explanation">
		<h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

		<ul>
			<% book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
		</div>
	 <% end %>
	<fieldset>
	<legend>Enter Book Details</legend>

  <div class="field">
    <%= form.label :book_name , 'Title'%>
    <%= form.text_field :book_name %>
  </div>

  <div class="field">
    <%= form.label :book_image, 'Image' %>
    <%= form.text_field :book_image%>
  </div>

  <div class="field">
    <%= form.label :cartegory_id, 'Type' %>
    <%= form.select :cartegory_id, @cartegories.collect{|cartegory| [cartegory.name, cartegory.id]}, :prompt => "Select a book type..." %>
  </div>

  <div class="field">
    <%= form.label :book_author ,'Author'%>
    <%= form.text_field :book_author %>
  </div>

  <div class="field">
    <%= form.label :book_price, 'Price' %>
    <%= form.text_field :book_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
</fieldset>
<% end %>
</div>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Book name</th>
      <th>Book image</th>
      <th>Book type</th>
      <th>Book author</th>
      <th>Book price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.book_name %></td>
        <td><%= book.book_image %></td>
        <td><%= book.cartegory.name %></td>
        <td><%= book.book_author %></td>
        <td><%= book.book_price %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book name:</strong>
  <%= @book.book_name %>
</p>

<p>
  <strong>Book image:</strong>
  <%= @book.book_image %>
</p>

<p>
  <strong>Book type:</strong>
  <%= @book.cartegory.name %>
</p>

<p>
  <strong>Book author:</strong>
  <%= @book.book_author %>
</p>

<p>
  <strong>Book price:</strong>
  <%= @book.book_price %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>