config/routes.rb
Rails.application.routes.draw do
  get 'session/new'
  get 'session/create'
  get 'session/destroy'
  get 'admin/index'
  resources :users
  get 'manager/index'
  resources :books
  resources :cartegories
  root to: 'manager#index'
  
   get 'admin' => 'admin#index'
    get 'register' => 'users#new'
      controller :session do
        get 'login' => :new
        post 'login' => :create
        delete 'logout' => :destroy
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cartegory.rb
class Cartegory < ApplicationRecord
	has_many :books
	before_save :init
	before_destroy :check_if_has_book
private
	def init
		self.parent_id = 0 unless self.parent_id
	end
	def check_if_has_book
		if books.empty?
			return true
		else
			errors.add(base,"Không được xóa khi chưa xóa hết sách trong cart")
			return false
		end
	end
end

app/controllers/cartegories_controller.rb
class CartegoriesController < ApplicationController
  before_action :set_cartegory, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /cartegories
  # GET /cartegories.json
  def index
    @cartegories = Cartegory.all
  end

  # GET /cartegories/1
  # GET /cartegories/1.json
  def show
  end

  # GET /cartegories/new
  def new
    @cartegories = Cartegory.all
    @cartegory = Cartegory.new
  end

  # GET /cartegories/1/edit
  def edit
    @cartegories = Cartegory.all
  end

  # POST /cartegories
  # POST /cartegories.json
  def create
    @cartegory = Cartegory.new(cartegory_params)

    respond_to do |format|
      if @cartegory.save
        format.html { redirect_to @cartegory, notice: 'Cartegory was successfully created.' }
        format.json { render :show, status: :created, location: @cartegory }
      else
        format.html { render :new }
        format.json { render json: @cartegory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cartegories/1
  # PATCH/PUT /cartegories/1.json
  def update
    respond_to do |format|
      if @cartegory.update(cartegory_params)
        format.html { redirect_to @cartegory, notice: 'Cartegory was successfully updated.' }
        format.json { render :show, status: :ok, location: @cartegory }
      else
        format.html { render :edit }
        format.json { render json: @cartegory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cartegories/1
  # DELETE /cartegories/1.json
  def destroy
    @cartegory.destroy
    respond_to do |format|
      format.html { redirect_to cartegories_url, notice: 'Cartegory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cartegory
      @cartegory = Cartegory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cartegory_params
      params.require(:cartegory).permit(:name, :parent_id)
    end
end

app/helpers/cartegories_helper.rb
module CartegoriesHelper
end

app/views/cartegories/_cartegory.html.erb
<ul id = "cart_menu">
	<% @cartegories.each do |cartegory| %>
		<li class = "cart_item" ><a href = "#"><%=cartegory.cart_type%><li>
	<% end %>
	<li><%= link_to "Add a cartegory...", new_cartegory_path %><li>
</ul>

app/views/cartegories/_form.html.erb
<%= form_with(model: cartegory, local: true) do |form| %>
  <% if cartegory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cartegory.errors.count, "error") %> prohibited this cartegory from being saved:</h2>

      <ul>
      <% cartegory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name , 'Name'%>
    <%= form.text_field :name %>
  </div>

  
  <div class="field">
    <%= form.label :cartegory_id, 'Parent cartegory' %>
    <%= form.select :cartegory_id, @cartegories.collect{|cartegory| [cartegory.name, cartegory.id]}, :prompt => "Select a cartegory" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cartegories/edit.html.erb
<h1>Editing Cartegory</h1>

<%= render 'form', cartegory: @cartegory %>

<%= link_to 'Show', @cartegory %> |
<%= link_to 'Back', cartegories_path %>

app/views/cartegories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cartegories</h1>

<table>
  <thead>
    <tr>
      <th>Cart type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cartegories.each do |cartegory| %>
        <%@carts = Cartegory.where(parent_id:cartegory.id)%>
        <%unless @carts.empty?%>
          <td><strong><%= cartegory.name %><strong></td>
          <% @carts.each do |cart| %>
            <tr>
            <td><%= cart.name %></td>
            <td><%= link_to 'Show', cart %></td>
            <td><%= link_to 'Edit', edit_cartegory_path(cart) %></td>
            <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
         <%end%>
        <%else%>
          <% if cartegory.parent_id == 0 %>
          <td><strong><%= cartegory.name %><strong></td>
          <td><%= link_to 'Show', cartegory %></td>
          <td><%= link_to 'Edit', edit_cartegory_path(cartegory) %></td>
          <td><%= link_to 'Destroy', cartegory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <%end%>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cartegory', new_cartegory_path %>

app/views/cartegories/new.html.erb
<h1>New Cartegory</h1>

<%= render 'form', cartegory: @cartegory %>

<%= link_to 'Back', cartegories_path %>

app/views/cartegories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= @cartegory.name %></strong>
</p>
	<table>
		<tbody>
			<% @cartegory.books.each do |book| %>
				<tr class = "<%= cycle('list_line_odd','list_line_even')%>">
					<td>
						<%= image_tag(book.book_image, :class => 'list_image') %>
					</td>
					<td class = "list_description">
						<dl>
							<dt><%= book.book_name %></dt>
							<dd>Tác giả: <%= book.book_author %></dd>
							<dd>Thể loại: <%= book.cartegory.name %></dd>
							<dd><colspan="4"></dd>
						<dl>
						<div class="prince_line">
							<span class = "price"><%= number_to_currency(book.book_price)%></span>
						</div>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
<%= link_to 'Edit', edit_cartegory_path(@cartegory) %> |
<%= link_to 'New Book', new_book_path(@cartegory) %> |
<%= link_to 'Back', cartegories_path %>